class Config:
    SECRET_KEY = "CREATE YOUR OWN SECRET KEY"

    MONGO_URI = "YOUR MONGO-DB URL"
    DB_NAME = "private_vault"

    MAIL_SERVER = 'smtp.gmail.com'
    MAIL_PORT = 587
    MAIL_USE_TLS = True
    MAIL_USERNAME = 'GMAIL'
    MAIL_PASSWORD = 'APP PASSWORD'

    CLOUDINARY_CLOUD_NAME = ""
    CLOUDINARY_API_KEY = ""
    CLOUDINARY_API_SECRET = ""
